version: '3.3'
services:
    broker :
        image : eclipse-mosquitto
        hostname : broker
        container_name : broker
        expose :
            - "1883"
        ports :
            - 6502:1883
        volumes :
            - /home/diot/Desktop/priya/mosquitto.conf:/mosquitto/config/mosquitto.conf
    subscriber1 :
        build : ./subscriber
        container_name : subscriber1
        hostname : sub
        depends_on :
            - broker
